apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercises
  template:
    metadata:
      labels:
        app: exercises
    spec:
      containers:
        - name: exercises
          image: lina4281/challenge-exercises-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: exercises
spec:
  selector:
    app: exercises
  ports:
    - port: 8081
      targetPort: 8081
  type: NodePort